CapCatToSameOrg = {
    "Met": "WXR",
    "Admin": "EAS",
    "Other": "CIV",
}

CapEventToSameEvent = {
    "civilEmerg": "CEM",
	"terrorism": "CDW",
	"animalDang": "CDW",
	"wildFire": "FRW",
	"industryFire": "IFW",
	"urbanFire": "FRW",
	"forestFire": "FRW",
	"stormSurge": "SSW",
	"flashFlood": "FFW",
	"damOverflow": "DBW",
	"earthquake": "EQW",
	"magnetStorm": "CDW",
	"landslide": "FLW",
	"meteor": "CDW",
	"tsunami": "TSW",
	"lahar": "VOW",
	"pyroclasticS": "VOW",
	"pyroclasticF": "VOW",
	"volcanicAsh": "VOW",
	"chemical": "CHW",
	"biological": "BHW",
	"radiological": "RHW",
	"explosives": "HMW",
	"fallObject": "HMW",
	"drinkingWate": "CWW",
	"amber": "CAE",
	"hurricane": "HUW",
	"thunderstorm": "SVR",
	"tornado": "TOR",
	"testMessage": "ADR",
	"911Service": "TOE",
	"weather": "SPS",
    "squall": "SMW",
}
